name: Perform tests
on:
  workflow_run:
    workflows: ["Update Submodules"]
    types:
      - completed


permissions:
  contents: write

jobs:
  update:
    name: Perform tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run tests
        run: |
          pip install pytest
          pytest
#something:D
#something more ^^

