name: Perform tests
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:


permissions:
  contents: write

jobs:
  test:
    name: Perform tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Update submodules to latest commit on main and commit if necessary
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule sync --recursive
          git submodule update --init --remote --recursive

          if [ -n "$(git status --porcelain)" ]; then
            echo "Submodules have new commits. Committing and pushing..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: update submodules to latest main"
            git push
          else
            echo "No submodule changes."
          fi

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run tests
        id: run_tests
        run: |
          pip install pytest
          ls -la
          pytest

