name: Update Submodules
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update Submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: false


